name: darknav
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - numpy
  - pillow
  - matplotlib
  - opencv              # cv2 with imshow support
  - opencv-python-headless
  - tqdm
  - scipy
  - pip
  - pip:
      - open3d>=0.17    # point clouds (optional for later)
      - vedo            # lightweight viz (optional)