name: darknav
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - numpy
  - pillow
  - matplotlib
    - opencv                  # cv2 with imshow support
  - opencv-python-headless
  - tqdm
  - scipy
  - pytorch=2.5
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip
  - pip:
      - open3d>=0.17
      - vedo
      - transformers>=4.44.0   # For LMM support alter
      - accelerate>=0.33.0